steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-f'
      - 'backend/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/amazon-ppc-backend:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/amazon-ppc-backend:$COMMIT_SHA'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/amazon-ppc-backend:latest'
  - 'gcr.io/$PROJECT_ID/amazon-ppc-backend:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
